name: Greet everyone
# This workflow is triggered on pushes to the repository.
on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - develop

jobs:
  build:
    # Job name is Greeting
    name: Test
    # This job runs on linux
    runs-on: ubuntu-latest
    steps:
      - name: test
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm test
        id: test-step
